version: '3'
services:
    influxdb:
        image: influxdb
        ports:
            - 8086:8086
        volumes:
            - ./influxdb-data:/var/lib/influxdb
        env_file:
            - .env
